{"abstract":[{"text":"The location where the error was thrown.","type":"text"}],"variants":[{"paths":["\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting"]]},"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"NIOHTTP2"}],"symbolKind":"property","externalID":"s:8NIOHTTP20A6ErrorsO24PushInViolationOfSettingV8locationSSvp","title":"location"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting":{"navigatorTitle":[{"kind":"identifier","text":"PushInViolationOfSetting"}],"role":"symbol","kind":"symbol","abstract":[{"text":"An attempt was made to push a stream, even though the settings forbid it.","type":"text"}],"title":"NIOHTTP2Errors.PushInViolationOfSetting","type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushInViolationOfSetting"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","role":"collection","title":"NIOHTTP2","url":"\/documentation\/niohttp2","abstract":[],"kind":"symbol","type":"topic"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"navigatorTitle":[{"text":"NIOHTTP2Errors","kind":"identifier"}],"type":"topic","title":"NIOHTTP2Errors","abstract":[{"type":"text","text":"Errors that NIO raises when handling HTTP\/2 connections."}],"url":"\/documentation\/niohttp2\/niohttp2errors","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NIOHTTP2Errors","kind":"identifier"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/PushInViolationOfSetting/location":{"role":"symbol","kind":"symbol","abstract":[{"text":"The location where the error was thrown.","type":"text"}],"title":"location","type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors\/pushinviolationofsetting\/location","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/PushInViolationOfSetting\/location","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}}}